In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
X,y = load_diabetes(return_X_y=True)
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [2]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [3]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [4]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [30]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [37]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=75)

In [11]:
int(X_train.shape[0]/10)

35

In [39]:
mbr.fit(X_train,y_train)

148.65896096436006 [  43.2523708  -115.65262594  417.35700917  280.34942416   -3.49367466
  -63.48065923 -187.86447116  125.89017024  373.79878148  124.30391344]


In [40]:
r2_score(y_test,mbr.predict(X_test))

0.44747652395703474

In [41]:
from sklearn.linear_model import SGDRegressor

In [42]:
m=SGDRegressor(learning_rate='constant',eta0=0.1)

In [47]:
batch_size=35

for i in range(100):
    idx = random.sample(range(X_train.shape[0]),batch_size)
    m.partial_fit(X_train[idx],y_train[idx])

In [50]:
m.coef_

array([  39.21608182,  -69.26932448,  346.21286457,  244.7369296 ,
         16.9078211 ,  -33.38538912, -154.88259898,  123.93579141,
        302.17587686,  119.26728185])

In [51]:
m.intercept_

array([142.47154676])

In [52]:
m.predict(X_test)

array([144.22787055, 181.70078942, 129.59366467, 102.42261669,
       230.5049796 , 222.90233559, 101.29675505, 107.20622934,
        87.47466145, 174.12309644, 149.7779769 , 161.10027705,
       172.65113294, 139.43751679, 240.68690226,  87.15701786,
       175.46321831, 131.30006646, 130.76946305, 129.33118166,
       125.47460953, 177.81205696, 154.65407   , 166.44225841,
       118.88336387, 206.03539641, 184.03122406, 112.62714255,
        58.45231648, 226.98127953, 222.24237077, 111.21299969,
        70.11797022, 102.64429176, 187.24750321, 155.33535906,
       156.35388389, 183.09713828, 108.02233415, 217.81254629,
       129.03991809, 118.31367791, 174.44567384, 174.797193  ,
       159.14056084, 136.68291505, 162.15496947, 261.49898219,
       109.35225674, 175.12554377, 223.6056281 , 123.82945727,
       135.81506671, 137.7954359 , 177.33914957, 105.10961348,
       144.16499529,  81.14986451, 149.34422212, 136.29157497,
       152.83836543, 159.69051507, 103.68604338, 194.24

In [53]:
r2_score(y_test,y_pred)

0.4399338661568968